name: persian_fonts
description: A Flutter package for using free persian fonts. It supports Vazir, Samim, Shabnam and Sahel fonts.
version: 1.0.3
homepage: https://github.com/mahdyar/persian-fonts-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: Vazir
      fonts:
        - asset: lib/fonts/Vazir.ttf
    - family: Samim
      fonts:
        - asset: lib/fonts/Samim.ttf
    - family: Shabnam
      fonts:
        - asset: lib/fonts/Shabnam.ttf
    - family: Sahel
      fonts:
        - asset: lib/fonts/Sahel.ttf