import 'package:flutter/material.dart';

// This file is automatically generated!

class PersianFonts extends TextStyle {
  static const Vazir = TextStyle(fontFamily: 'Vazir', package: 'persian_fonts');

/*
 Vazir Font: https://github.com/rastikerdar/vazir-font
*/

  static TextTheme vazirTextTheme = TextTheme(
    headline2: PersianFonts.Vazir,
    headline3: PersianFonts.Vazir,
    headline1: PersianFonts.Vazir,
    headline4: PersianFonts.Vazir,
    headline5: PersianFonts.Vazir,
    headline6: PersianFonts.Vazir,
    subtitle1: PersianFonts.Vazir,
    subtitle2: PersianFonts.Vazir,
    bodyText1: PersianFonts.Vazir,
    bodyText2: PersianFonts.Vazir,
    caption: PersianFonts.Vazir,
    button: PersianFonts.Vazir,
    overline: PersianFonts.Vazir,
  );

/*
 Samim Font: https://github.com/rastikerdar/samim-font
*/

  static const Samim = TextStyle(fontFamily: 'Samim', package: 'persian_fonts');

  static TextTheme samimTextTheme = TextTheme(
    headline2: PersianFonts.Samim,
    headline3: PersianFonts.Samim,
    headline1: PersianFonts.Samim,
    headline4: PersianFonts.Samim,
    headline5: PersianFonts.Samim,
    headline6: PersianFonts.Samim,
    subtitle1: PersianFonts.Samim,
    subtitle2: PersianFonts.Samim,
    bodyText1: PersianFonts.Samim,
    bodyText2: PersianFonts.Samim,
    caption: PersianFonts.Samim,
    button: PersianFonts.Samim,
    overline: PersianFonts.Samim,
  );

/*
 Shabnam Font: https://github.com/rastikerdar/shabnam-font
*/

  static const Shabnam =
      TextStyle(fontFamily: 'Shabnam', package: 'persian_fonts');

  static TextTheme shabnamTextTheme = TextTheme(
    headline2: PersianFonts.Shabnam,
    headline3: PersianFonts.Shabnam,
    headline1: PersianFonts.Shabnam,
    headline4: PersianFonts.Shabnam,
    headline5: PersianFonts.Shabnam,
    headline6: PersianFonts.Shabnam,
    subtitle1: PersianFonts.Shabnam,
    subtitle2: PersianFonts.Shabnam,
    bodyText1: PersianFonts.Shabnam,
    bodyText2: PersianFonts.Shabnam,
    caption: PersianFonts.Shabnam,
    button: PersianFonts.Shabnam,
    overline: PersianFonts.Shabnam,
  );

/*
 Sahel Font: https://github.com/rastikerdar/sahel-font 
*/

  static const Sahel = TextStyle(fontFamily: 'Sahel', package: 'persian_fonts');

  static TextTheme sahelTextTheme = TextTheme(
    headline2: PersianFonts.Sahel,
    headline3: PersianFonts.Sahel,
    headline1: PersianFonts.Sahel,
    headline4: PersianFonts.Sahel,
    headline5: PersianFonts.Sahel,
    headline6: PersianFonts.Sahel,
    subtitle1: PersianFonts.Sahel,
    subtitle2: PersianFonts.Sahel,
    bodyText1: PersianFonts.Sahel,
    bodyText2: PersianFonts.Sahel,
    caption: PersianFonts.Sahel,
    button: PersianFonts.Sahel,
    overline: PersianFonts.Sahel,
  );

/*
  B-Yekan(Yekan) Font
*/

  static const Yekan = TextStyle(fontFamily: 'Yekan', package: 'persian_fonts');

  static TextTheme yekanTextTheme = TextTheme(
    headline2: PersianFonts.Yekan,
    headline3: PersianFonts.Yekan,
    headline1: PersianFonts.Yekan,
    headline4: PersianFonts.Yekan,
    headline5: PersianFonts.Yekan,
    headline6: PersianFonts.Yekan,
    subtitle1: PersianFonts.Yekan,
    subtitle2: PersianFonts.Yekan,
    bodyText1: PersianFonts.Yekan,
    bodyText2: PersianFonts.Yekan,
    caption: PersianFonts.Yekan,
    button: PersianFonts.Yekan,
    overline: PersianFonts.Yekan,
  );
}
