import 'package:flutter/material.dart';

// This file is automatically generated!

class PersianFonts extends TextStyle {
  static const Vazir = TextStyle(fontFamily: 'Vazir', package: 'persian_fonts');

/*
 Vazir Font: https://github.com/rastikerdar/vazir-font
*/

  static TextTheme vazirTextTheme = TextTheme(
    displayMedium: PersianFonts.Vazir,
    displaySmall: PersianFonts.Vazir,
    displayLarge: PersianFonts.Vazir,
    headlineMedium: PersianFonts.Vazir,
    headlineSmall: PersianFonts.Vazir,
    titleLarge: PersianFonts.Vazir,
    titleMedium: PersianFonts.Vazir,
    titleSmall: PersianFonts.Vazir,
    bodyLarge: PersianFonts.Vazir,
    bodyMedium: PersianFonts.Vazir,
    bodySmall: PersianFonts.Vazir,
    labelLarge: PersianFonts.Vazir,
    labelSmall: PersianFonts.Vazir,
  );

/*
 Samim Font: https://github.com/rastikerdar/samim-font
*/

  static const Samim = TextStyle(fontFamily: 'Samim', package: 'persian_fonts');

  static TextTheme samimTextTheme = TextTheme(
    displayMedium: PersianFonts.Samim,
    displaySmall: PersianFonts.Samim,
    displayLarge: PersianFonts.Samim,
    headlineMedium: PersianFonts.Samim,
    headlineSmall: PersianFonts.Samim,
    titleLarge: PersianFonts.Samim,
    titleMedium: PersianFonts.Samim,
    titleSmall: PersianFonts.Samim,
    bodyLarge: PersianFonts.Samim,
    bodyMedium: PersianFonts.Samim,
    bodySmall: PersianFonts.Samim,
    labelLarge: PersianFonts.Samim,
    labelSmall: PersianFonts.Samim,
  );

/*
 Shabnam Font: https://github.com/rastikerdar/shabnam-font
*/

  static const Shabnam =
      TextStyle(fontFamily: 'Shabnam', package: 'persian_fonts');

  static TextTheme shabnamTextTheme = TextTheme(
    displayMedium: PersianFonts.Shabnam,
    displaySmall: PersianFonts.Shabnam,
    displayLarge: PersianFonts.Shabnam,
    headlineMedium: PersianFonts.Shabnam,
    headlineSmall: PersianFonts.Shabnam,
    titleLarge: PersianFonts.Shabnam,
    titleMedium: PersianFonts.Shabnam,
    titleSmall: PersianFonts.Shabnam,
    bodyLarge: PersianFonts.Shabnam,
    bodyMedium: PersianFonts.Shabnam,
    bodySmall: PersianFonts.Shabnam,
    labelLarge: PersianFonts.Shabnam,
    labelSmall: PersianFonts.Shabnam,
  );

/*
 Sahel Font: https://github.com/rastikerdar/sahel-font 
*/

  static const Sahel = TextStyle(fontFamily: 'Sahel', package: 'persian_fonts');

  static TextTheme sahelTextTheme = TextTheme(
    displayMedium: PersianFonts.Sahel,
    displaySmall: PersianFonts.Sahel,
    displayLarge: PersianFonts.Sahel,
    headlineMedium: PersianFonts.Sahel,
    headlineSmall: PersianFonts.Sahel,
    titleLarge: PersianFonts.Sahel,
    titleMedium: PersianFonts.Sahel,
    titleSmall: PersianFonts.Sahel,
    bodyLarge: PersianFonts.Sahel,
    bodyMedium: PersianFonts.Sahel,
    bodySmall: PersianFonts.Sahel,
    labelLarge: PersianFonts.Sahel,
    labelSmall: PersianFonts.Sahel,
  );

/*
  B-Yekan(Yekan) Font
*/

  static const Yekan = TextStyle(fontFamily: 'Yekan', package: 'persian_fonts');

  static TextTheme yekanTextTheme = TextTheme(
    displayMedium: PersianFonts.Yekan,
    displaySmall: PersianFonts.Yekan,
    displayLarge: PersianFonts.Yekan,
    headlineMedium: PersianFonts.Yekan,
    headlineSmall: PersianFonts.Yekan,
    titleLarge: PersianFonts.Yekan,
    titleMedium: PersianFonts.Yekan,
    titleSmall: PersianFonts.Yekan,
    bodyLarge: PersianFonts.Yekan,
    bodyMedium: PersianFonts.Yekan,
    bodySmall: PersianFonts.Yekan,
    labelLarge: PersianFonts.Yekan,
    labelSmall: PersianFonts.Yekan,
  );
}
